import Hero from '@/components/Hero'
import LowerNav from '@/components/LowerNav'
import NavBar from '@/components/NavBar'
import ProductFeed from '@/components/ProductFeed'
import Head from 'next/head'


export default function Home({products}) {
  console.log(products)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <NavBar />
     <LowerNav />
     <Hero />
     <ProductFeed products={products} />
    </>
  )
}

export async function getServerSideProps(context) {
 const products =await fetch('https://fakestoreapi.com/products').then((res)=>(
  res.json()
 ))
  return {
    props: {
      products,
    },
  };
}